# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
title: Arquitectura de Microservicios
description: Traducción al español de las publicaciones de Chris Richardson en http://microservices.io/patterns/index.html
baseurl: "/microservice-architecture-es"
